import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MCPStatus from "@/components/MCPStatus";
import MonkeytypeHeader from '@/components/common/MonkeytypeHeader';
import MinimalShortcut from '@/components/MinimalShortcut';
import styles from "@/styles/TypingGame.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className={styles.appContainer}>
          <MonkeytypeHeader />
          {children}
          {/* 画面ごとのショートカット表示に統一するため削除 */}
          <div className={styles.mcpStatusWrapper}>
            <MCPStatus position="bottom-right" />
          </div>
        </div>
      </body>
    </html>
  );
}
